// web/app/components/Mermaid.vue
<script setup lang="ts">
import type mermaidType from 'mermaid'

// Ported from src/components/Mermaid.tsx. Renders a mermaid chart to SVG, with a
// click-to-fullscreen modal (wheel/buttons zoom) and optional svg-pan-zoom.

const props = withDefaults(defineProps<{
  chart: string
  className?: string
  zoomingEnabled?: boolean
}>(), {
  className: '',
  zoomingEnabled: false,
})

const THEME_CSS = `
    /* Japanese aesthetic styles for all diagrams */
    .node rect, .node circle, .node ellipse, .node polygon, .node path {
      fill: #f8f4e6;
      stroke: var(--accent-secondary);
      stroke-width: 1px;
    }
    .edgePath .path { stroke: var(--accent-primary); stroke-width: 1.5px; }
    .edgeLabel { background-color: transparent; color: #333333; p { background-color: transparent !important; } }
    .label { color: #333333; }
    .cluster rect { fill: #f8f4e6; stroke: var(--accent-secondary); stroke-width: 1px; }

    /* Sequence diagram specific styles */
    .actor { fill: #f8f4e6; stroke: var(--accent-secondary); stroke-width: 1px; }
    text.actor { fill: #333333; stroke: none; }
    .messageText { fill: #333333; stroke: none; }
    .messageLine0, .messageLine1 { stroke: var(--accent-primary); }
    .noteText { fill: #333333; }

    /* Dark mode overrides - applied when the rendered <svg> carries data-theme="dark" */
    [data-theme="dark"] .node rect, [data-theme="dark"] .node circle, [data-theme="dark"] .node ellipse,
    [data-theme="dark"] .node polygon, [data-theme="dark"] .node path { fill: #222222; stroke: #5d4037; }
    [data-theme="dark"] .edgePath .path { stroke: var(--accent-primary); }
    [data-theme="dark"] .edgeLabel { background-color: transparent; color: #f0f0f0; }
    [data-theme="dark"] .label { color: #f0f0f0; }
    [data-theme="dark"] .cluster rect { fill: #222222; stroke: #5d4037; }
    [data-theme="dark"] .flowchart-link { stroke: var(--accent-primary); }

    [data-theme="dark"] .actor { fill: #222222; stroke: #5d4037; }
    [data-theme="dark"] text.actor { fill: #f0f0f0; stroke: none; }
    [data-theme="dark"] .messageText { fill: #f0f0f0; stroke: none; font-weight: 500; }
    [data-theme="dark"] .messageLine0, [data-theme="dark"] .messageLine1 { stroke: var(--accent-primary); stroke-width: 1.5px; }
    [data-theme="dark"] .noteText { fill: #f0f0f0; }
    [data-theme="dark"] #sequenceNumber { fill: #f0f0f0; }
    [data-theme="dark"] text.sequenceText { fill: #f0f0f0; font-weight: 500; }
    [data-theme="dark"] text.loopText, [data-theme="dark"] text.loopText tspan { fill: #f0f0f0; }
    [data-theme="dark"] .messageText, [data-theme="dark"] text.sequenceText {
      paint-order: stroke; stroke: #1a1a1a; stroke-width: 2px; stroke-linecap: round; stroke-linejoin: round;
    }

    /* Force text elements to be properly colored */
    text[text-anchor][dominant-baseline], text[text-anchor][alignment-baseline],
    .nodeLabel, .edgeLabel, .label, text { fill: #777 !important; }
    [data-theme="dark"] text[text-anchor][dominant-baseline], [data-theme="dark"] text[text-anchor][alignment-baseline],
    [data-theme="dark"] .nodeLabel, [data-theme="dark"] .edgeLabel, [data-theme="dark"] .label,
    [data-theme="dark"] text { fill: #f0f0f0 !important; }

    .clickable { transition: all 0.3s ease; }
    .clickable:hover { transform: scale(1.03); cursor: pointer; }
    .clickable:hover > * { filter: brightness(0.95); }
`

// Initialize mermaid exactly once, lazily, on the client.
let mermaidReady: Promise<typeof mermaidType> | null = null
function ensureMermaid(): Promise<typeof mermaidType> {
  if (!mermaidReady) {
    mermaidReady = import('mermaid').then((m) => {
      const mermaid = m.default
      mermaid.initialize({
        startOnLoad: false,
        theme: 'neutral',
        securityLevel: 'loose',
        suppressErrorRendering: true,
        logLevel: 'error',
        maxTextSize: 100000,
        htmlLabels: true,
        flowchart: { htmlLabels: true, curve: 'basis', nodeSpacing: 60, rankSpacing: 60, padding: 20 },
        themeCSS: THEME_CSS,
        fontFamily: 'var(--font-geist-sans), var(--font-serif-jp), sans-serif',
        fontSize: 12,
      })
      return mermaid
    })
  }
  return mermaidReady
}

// Strip artifacts the LLM sometimes appends inside a ```mermaid block (e.g. a
// trailing "Sources: [file](...)" citation line), which break Mermaid parsing.
function cleanMermaidChart(raw: string): string {
  const lines = (raw || '').split('\n')
  const out: string[] = []
  for (const line of lines) {
    if (/^\s*sources?\s*[:：]/i.test(line)) break
    out.push(line)
  }
  return out.join('\n').trim()
}

const colorMode = useColorMode()
const svg = ref('')
const error = ref<string | null>(null)
const isFullscreen = ref(false)
const containerRef = ref<HTMLDivElement | null>(null)
const id = `mermaid-${Math.random().toString(36).substring(2, 9)}`

const ZOOM_MIN = 0.5
const ZOOM_MAX = 5
const zoom = ref(1)

async function renderChart() {
  if (!props.chart) return
  try {
    error.value = null
    svg.value = ''
    const mermaid = await ensureMermaid()
    const cleaned = cleanMermaidChart(props.chart)
    const { svg: rendered } = await mermaid.render(id, cleaned)
    // Tag the SVG so the dark-mode themeCSS rules apply.
    svg.value = colorMode.value === 'dark'
      ? rendered.replace('<svg ', '<svg data-theme="dark" ')
      : rendered
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    error.value = `Failed to render diagram: ${message}`
    // eslint-disable-next-line no-console
    console.error('Mermaid rendering error:', err)
  }
}

// Pan-zoom (inline mode only): attach svg-pan-zoom once the SVG is in the DOM.
async function initPanZoom() {
  if (!props.zoomingEnabled || !svg.value || !containerRef.value) return
  await nextTick()
  const svgElement = containerRef.value.querySelector('svg')
  if (!svgElement) return
  svgElement.style.maxWidth = 'none'
  svgElement.style.width = '100%'
  svgElement.style.height = '100%'
  try {
    const svgPanZoom = (await import('svg-pan-zoom')).default
    svgPanZoom(svgElement, {
      zoomEnabled: true,
      controlIconsEnabled: true,
      fit: true,
      center: true,
      minZoom: 0.1,
      maxZoom: 10,
      zoomScaleSensitivity: 0.3,
    })
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error('Failed to load svg-pan-zoom:', e)
  }
}

onMounted(() => {
  // Re-render on chart or theme change (theme flips the injected data-theme attr).
  watch(() => [props.chart, colorMode.value], renderChart, { immediate: true })
  watch(svg, () => { if (props.zoomingEnabled) setTimeout(() => void initPanZoom(), 100) })

  // Esc closes the fullscreen modal.
  const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') isFullscreen.value = false }
  window.addEventListener('keydown', onKey)
  onBeforeUnmount(() => window.removeEventListener('keydown', onKey))
})

watch(isFullscreen, (open) => { if (open) zoom.value = 1 })

function openFullscreen() {
  if (!error.value && svg.value && !props.zoomingEnabled) isFullscreen.value = true
}
function zoomIn() { zoom.value = Math.min(ZOOM_MAX, Math.round((zoom.value + 0.1) * 100) / 100) }
function zoomOut() { zoom.value = Math.max(ZOOM_MIN, Math.round((zoom.value - 0.1) * 100) / 100) }
function zoomReset() { zoom.value = 1 }
function onWheel(e: WheelEvent) {
  const next = zoom.value - e.deltaY * 0.0015
  zoom.value = Math.round(Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, next)) * 100) / 100
}
</script>

<template>
  <!-- Error state -->
  <div
    v-if="error"
    :class="`border border-[var(--highlight)]/30 rounded-md p-4 bg-[var(--highlight)]/5 ${className}`"
  >
    <div class="flex items-center mb-3">
      <div class="text-[var(--highlight)] text-xs font-medium flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        图表渲染错误
      </div>
    </div>
    <pre class="text-xs overflow-auto p-2 bg-gray-100 dark:bg-gray-800 rounded">{{ props.chart }}</pre>
    <div class="mt-3 text-xs text-[var(--muted)] font-serif-jp">图表存在语法错误，无法渲染。</div>
  </div>

  <!-- Loading state -->
  <div v-else-if="!svg" :class="`flex justify-center items-center p-4 ${className}`">
    <div class="flex items-center space-x-2">
      <div class="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse" />
      <div class="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse delay-75" />
      <div class="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse delay-150" />
      <span class="text-[var(--muted)] text-xs ml-2 font-serif-jp">图表渲染中...</span>
    </div>
  </div>

  <!-- Rendered diagram -->
  <template v-else>
    <div ref="containerRef" :class="`w-full max-w-full ${zoomingEnabled ? 'h-[600px] p-4' : ''}`">
      <div :class="`relative group ${zoomingEnabled ? 'h-full rounded-lg border-2 border-black' : ''}`">
        <!-- eslint-disable-next-line vue/no-v-html -->
        <div
          :class="`flex justify-center overflow-auto text-center hover:shadow-md transition-shadow duration-200 rounded-md ${className} ${zoomingEnabled ? 'h-full' : 'cursor-zoom-in'}`"
          :title="zoomingEnabled ? undefined : '点击查看大图'"
          @click="openFullscreen"
          v-html="svg"
        />
        <div
          v-if="!zoomingEnabled"
          class="absolute top-2 right-2 bg-gray-700/70 dark:bg-gray-900/70 text-white p-1.5 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center gap-1.5 text-xs shadow-md pointer-events-none"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
            <line x1="11" y1="8" x2="11" y2="14" /><line x1="8" y1="11" x2="14" y2="11" />
          </svg>
          <span>点击放大</span>
        </div>
      </div>
    </div>

    <!-- Fullscreen modal -->
    <Teleport to="body">
      <div
        v-if="isFullscreen && !zoomingEnabled"
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"
        @click.self="isFullscreen = false"
      >
        <div class="bg-[var(--card-bg)] rounded-lg shadow-custom w-[95vw] max-w-[1600px] h-[90vh] overflow-hidden flex flex-col card-japanese">
          <div class="flex items-center justify-between p-4 border-b border-[var(--border-color)]">
            <div class="flex items-center gap-2 font-medium text-[var(--foreground)] font-serif-jp">
              图表
              <span class="text-xs font-normal text-[var(--muted)]">（滚动鼠标滚轮可缩放）</span>
            </div>
            <div class="flex items-center gap-4">
              <div class="flex items-center gap-2">
                <button class="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors" aria-label="Zoom out" @click="zoomOut">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /><line x1="8" y1="11" x2="14" y2="11" />
                  </svg>
                </button>
                <span class="text-sm text-[var(--muted)]">{{ Math.round(zoom * 100) }}%</span>
                <button class="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors" aria-label="Zoom in" @click="zoomIn">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /><line x1="11" y1="8" x2="11" y2="14" /><line x1="8" y1="11" x2="14" y2="11" />
                  </svg>
                </button>
                <button class="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors" aria-label="Reset zoom" @click="zoomReset">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8" /><path d="M21 3v5h-5" />
                  </svg>
                </button>
              </div>
              <button class="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors" aria-label="Close" @click="isFullscreen = false">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            </div>
          </div>
          <div class="overflow-auto p-6 flex-1 flex items-center justify-center bg-[var(--background)]/50" @wheel.prevent="onWheel">
            <!-- eslint-disable-next-line vue/no-v-html -->
            <div
              class="w-full h-full flex items-center justify-center [&>svg]:!w-full [&>svg]:!h-full [&>svg]:!max-w-full [&>svg]:!max-h-full"
              :style="{ transform: `scale(${zoom})`, transformOrigin: 'center center', transition: 'transform 0.1s ease-out' }"
              v-html="svg"
            />
          </div>
        </div>
      </div>
    </Teleport>
  </template>
</template>

// src/components/Mermaid.tsx
import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
// We'll use dynamic import for svg-pan-zoom

// Initialize mermaid with defaults - Japanese aesthetic
mermaid.initialize({
  startOnLoad: true,
  theme: 'neutral',
  securityLevel: 'loose',
  suppressErrorRendering: true,
  logLevel: 'error',
  maxTextSize: 100000, // Increase text size limit
  htmlLabels: true,
  flowchart: {
    htmlLabels: true,
    curve: 'basis',
    nodeSpacing: 60,
    rankSpacing: 60,
    padding: 20,
  },
  themeCSS: `
    /* Japanese aesthetic styles for all diagrams */
    .node rect, .node circle, .node ellipse, .node polygon, .node path {
      fill: #f8f4e6;
      stroke: var(--accent-secondary);
      stroke-width: 1px;
    }
    .edgePath .path {
      stroke: var(--accent-primary);
      stroke-width: 1.5px;
    }
    .edgeLabel {
      background-color: transparent;
      color: #333333;
      p {
        background-color: transparent !important;
      }
    }
    .label {
      color: #333333;
    }
    .cluster rect {
      fill: #f8f4e6;
      stroke: var(--accent-secondary);
      stroke-width: 1px;
    }

    /* Sequence diagram specific styles */
    .actor {
      fill: #f8f4e6;
      stroke: var(--accent-secondary);
      stroke-width: 1px;
    }
    text.actor {
      fill: #333333;
      stroke: none;
    }
    .messageText {
      fill: #333333;
      stroke: none;
    }
    .messageLine0, .messageLine1 {
      stroke: var(--accent-primary);
    }
    .noteText {
      fill: #333333;
    }

    /* Dark mode overrides - will be applied with data-theme="dark" */
    [data-theme="dark"] .node rect,
    [data-theme="dark"] .node circle,
    [data-theme="dark"] .node ellipse,
    [data-theme="dark"] .node polygon,
    [data-theme="dark"] .node path {
      fill: #222222;
      stroke: #5d4037;
    }
    [data-theme="dark"] .edgePath .path {
      stroke: var(--accent-primary);
    }
    [data-theme="dark"] .edgeLabel {
      background-color: transparent;
      color: #f0f0f0;
    }
    [data-theme="dark"] .label {
      color: #f0f0f0;
    }
    [data-theme="dark"] .cluster rect {
      fill: #222222;
      stroke: #5d4037;
    }
    [data-theme="dark"] .flowchart-link {
      stroke: var(--accent-primary);
    }

    /* Dark mode sequence diagram overrides */
    [data-theme="dark"] .actor {
      fill: #222222;
      stroke: #5d4037;
    }
    [data-theme="dark"] text.actor {
      fill: #f0f0f0;
      stroke: none;
    }
    [data-theme="dark"] .messageText {
      fill: #f0f0f0;
      stroke: none;
      font-weight: 500;
    }
    [data-theme="dark"] .messageLine0, [data-theme="dark"] .messageLine1 {
      stroke: var(--accent-primary);
      stroke-width: 1.5px;
    }
    [data-theme="dark"] .noteText {
      fill: #f0f0f0;
    }
    /* Additional styles for sequence diagram text */
    [data-theme="dark"] #sequenceNumber {
      fill: #f0f0f0;
    }
    [data-theme="dark"] text.sequenceText {
      fill: #f0f0f0;
      font-weight: 500;
    }
    [data-theme="dark"] text.loopText, [data-theme="dark"] text.loopText tspan {
      fill: #f0f0f0;
    }
    /* Add a subtle background to message text for better readability */
    [data-theme="dark"] .messageText, [data-theme="dark"] text.sequenceText {
      paint-order: stroke;
      stroke: #1a1a1a;
      stroke-width: 2px;
      stroke-linecap: round;
      stroke-linejoin: round;
    }

    /* Force text elements to be properly colored */
    text[text-anchor][dominant-baseline],
    text[text-anchor][alignment-baseline],
    .nodeLabel,
    .edgeLabel,
    .label,
    text {
      fill: #777 !important;
    }

    [data-theme="dark"] text[text-anchor][dominant-baseline],
    [data-theme="dark"] text[text-anchor][alignment-baseline],
    [data-theme="dark"] .nodeLabel,
    [data-theme="dark"] .edgeLabel,
    [data-theme="dark"] .label,
    [data-theme="dark"] text {
      fill: #f0f0f0 !important;
    }

    /* Add clickable element styles with subtle transitions */
    .clickable {
      transition: all 0.3s ease;
    }
    .clickable:hover {
      transform: scale(1.03);
      cursor: pointer;
    }
    .clickable:hover > * {
      filter: brightness(0.95);
    }
  `,
  fontFamily: 'var(--font-geist-sans), var(--font-serif-jp), sans-serif',
  fontSize: 12,
});

interface MermaidProps {
  chart: string;
  className?: string;
  zoomingEnabled?: boolean;
}

// Full screen modal component for the diagram
const FullScreenModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  children: React.ReactNode;
}> = ({ isOpen, onClose, children }) => {
  const modalRef = useRef<HTMLDivElement>(null);
  const [zoom, setZoom] = useState(1);

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleKeyDown);
    }

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose]);

  // Handle click outside to close
  useEffect(() => {
    const handleOutsideClick = (e: MouseEvent) => {
      if (modalRef.current && !modalRef.current.contains(e.target as Node)) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleOutsideClick);
    }

    return () => {
      document.removeEventListener('mousedown', handleOutsideClick);
    };
  }, [isOpen, onClose]);

  // Reset zoom when modal opens
  useEffect(() => {
    if (isOpen) {
      setZoom(1);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-75 p-4">
      <div
        ref={modalRef}
        className="bg-[var(--card-bg)] rounded-lg shadow-custom max-w-5xl max-h-[90vh] w-full overflow-hidden flex flex-col card-japanese"
      >
        {/* Modal header with controls */}
        <div className="flex items-center justify-between p-4 border-b border-[var(--border-color)]">
          <div className="font-medium text-[var(--foreground)] font-serif">图表</div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setZoom(Math.max(0.5, zoom - 0.1))}
                className="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors"
                aria-label="Zoom out"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                  <line x1="8" y1="11" x2="14" y2="11"></line>
                </svg>
              </button>
              <span className="text-sm text-[var(--muted)]">{Math.round(zoom * 100)}%</span>
              <button
                onClick={() => setZoom(Math.min(2, zoom + 0.1))}
                className="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors"
                aria-label="Zoom in"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                  <line x1="11" y1="8" x2="11" y2="14"></line>
                  <line x1="8" y1="11" x2="14" y2="11"></line>
                </svg>
              </button>
              <button
                onClick={() => setZoom(1)}
                className="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors"
                aria-label="Reset zoom"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"></path>
                  <path d="M21 3v5h-5"></path>
                </svg>
              </button>
            </div>
            <button
              onClick={onClose}
              className="text-[var(--foreground)] hover:bg-[var(--accent-primary)]/10 p-2 rounded-md border border-[var(--border-color)] transition-colors"
              aria-label="Close"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18"></line>
                <line x1="6" y1="6" x2="18" y2="18"></line>
              </svg>
            </button>
          </div>
        </div>

        {/* Modal content with zoom */}
        <div className="overflow-auto p-6 flex-1 flex items-center justify-center bg-[var(--background)]/50">
          <div
            style={{
              transform: `scale(${zoom})`,
              transformOrigin: 'center center',
              transition: 'transform 0.3s ease-out'
            }}
          >
            {children}
          </div>
        </div>
      </div>
    </div>
  );
};

// Strip artifacts the LLM sometimes appends inside a ```mermaid block (e.g. a
// trailing "Sources: [file](...)" citation line), which break Mermaid parsing.
function cleanMermaidChart(raw: string): string {
  const lines = (raw || '').split('\n');
  const out: string[] = [];
  for (const line of lines) {
    if (/^\s*sources?\s*[:：]/i.test(line)) break; // stop at a "Sources:" citation line
    out.push(line);
  }
  return out.join('\n').trim();
}

const Mermaid: React.FC<MermaidProps> = ({ chart, className = '', zoomingEnabled = false }) => {
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const mermaidRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const idRef = useRef(`mermaid-${Math.random().toString(36).substring(2, 9)}`);
  const isDarkModeRef = useRef(
    typeof window !== 'undefined' &&
    window.matchMedia &&
    window.matchMedia('(prefers-color-scheme: dark)').matches
  );

  // Initialize pan-zoom functionality when SVG is rendered
  useEffect(() => {
    if (svg && zoomingEnabled && containerRef.current) {
      const initializePanZoom = async () => {
        const svgElement = containerRef.current?.querySelector("svg");
        if (svgElement) {
          // Remove any max-width constraints
          svgElement.style.maxWidth = "none";
          svgElement.style.width = "100%";
          svgElement.style.height = "100%";

          try {
            // Dynamically import svg-pan-zoom only when needed in the browser
            const svgPanZoom = (await import("svg-pan-zoom")).default;

            svgPanZoom(svgElement, {
              zoomEnabled: true,
              controlIconsEnabled: true,
              fit: true,
              center: true,
              minZoom: 0.1,
              maxZoom: 10,
              zoomScaleSensitivity: 0.3,
            });
          } catch (error) {
            console.error("Failed to load svg-pan-zoom:", error);
          }
        }
      };

      // Wait for the SVG to be rendered
      setTimeout(() => {
        void initializePanZoom();
      }, 100);
    }
  }, [svg, zoomingEnabled]);

  useEffect(() => {
    if (!chart) return;

    let isMounted = true;

    const renderChart = async () => {
      if (!isMounted) return;

      try {
        setError(null);
        setSvg('');

        // Clean LLM artifacts (e.g. a trailing "Sources:" citation line the model
        // sometimes appends inside the ```mermaid block) before rendering.
        const cleanedChart = cleanMermaidChart(chart);
        const { svg: renderedSvg } = await mermaid.render(idRef.current, cleanedChart);

        if (!isMounted) return;

        let processedSvg = renderedSvg;
        if (isDarkModeRef.current) {
          processedSvg = processedSvg.replace('<svg ', '<svg data-theme="dark" ');
        }

        setSvg(processedSvg);

        // Call mermaid.contentLoaded to ensure proper initialization
        setTimeout(() => {
          mermaid.contentLoaded();
        }, 50);
      } catch (err) {
        console.error('Mermaid rendering error:', err);

        const errorMessage = err instanceof Error ? err.message : String(err);

        if (isMounted) {
          setError(`Failed to render diagram: ${errorMessage}`);

          if (mermaidRef.current) {
            mermaidRef.current.innerHTML = `
              <div class="text-red-500 dark:text-red-400 text-xs mb-1">Syntax error in diagram</div>
              <pre class="text-xs overflow-auto p-2 bg-gray-100 dark:bg-gray-800 rounded">${chart}</pre>
            `;
          }
        }
      }
    };

    renderChart();

    return () => {
      isMounted = false;
    };
  }, [chart]);

  const handleDiagramClick = () => {
    if (!error && svg) {
      setIsFullscreen(true);
    }
  };

  if (error) {
    return (
      <div className={`border border-[var(--highlight)]/30 rounded-md p-4 bg-[var(--highlight)]/5 ${className}`}>
        <div className="flex items-center mb-3">
          <div className="text-[var(--highlight)] text-xs font-medium flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            图表渲染错误
          </div>
        </div>
        <div ref={mermaidRef} className="text-xs overflow-auto"></div>
        <div className="mt-3 text-xs text-[var(--muted)] font-serif">
          图表存在语法错误，无法渲染。
        </div>
      </div>
    );
  }

  if (!svg) {
    return (
      <div className={`flex justify-center items-center p-4 ${className}`}>
        <div className="flex items-center space-x-2">
          <div className="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse"></div>
          <div className="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse delay-75"></div>
          <div className="w-2 h-2 bg-[var(--accent-primary)]/70 rounded-full animate-pulse delay-150"></div>
          <span className="text-[var(--muted)] text-xs ml-2 font-serif">图表渲染中...</span>
        </div>
      </div>
    );
  }

  return (
    <>
      <div
        ref={containerRef}
        className={`w-full max-w-full ${zoomingEnabled ? "h-[600px] p-4" : ""}`}
      >
        <div
          className={`relative group ${zoomingEnabled ? "h-full rounded-lg border-2 border-black" : ""}`}
        >
          <div
            className={`flex justify-center overflow-auto text-center my-2 cursor-pointer hover:shadow-md transition-shadow duration-200 rounded-md ${className} ${zoomingEnabled ? "h-full" : ""}`}
            dangerouslySetInnerHTML={{ __html: svg }}
            onClick={zoomingEnabled ? undefined : handleDiagramClick}
            title={zoomingEnabled ? undefined : "Click to view fullscreen"}
          />

          {!zoomingEnabled && (
            <div className="absolute top-2 right-2 bg-gray-700/70 dark:bg-gray-900/70 text-white p-1.5 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center gap-1.5 text-xs shadow-md pointer-events-none">
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="11" cy="11" r="8"></circle>
                <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                <line x1="11" y1="8" x2="11" y2="14"></line>
                <line x1="8" y1="11" x2="14" y2="11"></line>
              </svg>
              <span>Click to zoom</span>
            </div>
          )}
        </div>
      </div>

      {!zoomingEnabled && (
        <FullScreenModal
          isOpen={isFullscreen}
          onClose={() => setIsFullscreen(false)}
        >
          <div dangerouslySetInnerHTML={{ __html: svg }} />
        </FullScreenModal>
      )}
    </>
  );
};



export default Mermaid;
